import { createContext, useEffect, useState } from "react";
export const GlobalContext = createContext()
export const GlobalContextProvider = ({children}) => {



    const resources = [
      { id: 1, nome: '🌳🌳 Curso em Vídeo, HTML5 e CSS3, Módulo 1/5', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O primeiro módulo do melhor curso de front para iniciantes, pelo melhor professor do mundo.', link: 'https://www.youtube.com/watch?v=Ejkb_YpuHWs&list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n&ab_channel=CursoemV%C3%ADdeo', tags: ['HTML', 'CSS', 'Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 2, nome: 'Curso em Vídeo, HTML5 e CSS3, Módulo 2/5', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O segundo módulo do melhor curso de front para iniciantes, pelo melhor professor do mundo.', link: 'https://www.youtube.com/watch?v=vPNIAJ9B4hg&list=PLHz_AreHm4dlUpEXkY1AyVLQGcpSgVF8s&ab_channel=CursoemV%C3%ADdeo', tags: ['HTML', 'CSS', 'Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 3, nome: 'Curso em Vídeo, HTML5 e CSS3, Módulo 3/5', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O terceiro módulo do melhor curso de front para iniciantes, pelo melhor professor do mundo.', link: 'https://www.youtube.com/watch?v=ofFgnDtn_1c&list=PLHz_AreHm4dmcAviDwiGgHbeEJToxbOpZ&ab_channel=CursoemV%C3%ADdeo', tags: ['HTML', 'CSS', 'Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 4, nome: 'Curso em Vídeo, HTML5 e CSS3, Módulo 4/5', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O quarto módulo do melhor curso de front para iniciantes, pelo melhor professor do mundo.', link: 'https://www.youtube.com/watch?v=zHKHMmEG9vE&list=PLHz_AreHm4dkcVCk2Bn_fdVQ81Fkrh6WT', tags: ['HTML', 'CSS', 'Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 5, nome: 'Curso em Vídeo, HTML5 e CSS3, Módulo 5/5!!!', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Finalmente saiu o QUINTO módulo do melhor curso de front para iniciantes, pelo melhor professor do mundo. E a coisa já começa quente com Flexbox!', link: 'https://www.youtube.com/watch?v=rqvn_c2n9Eg&list=PLHz_AreHm4dn1bAtIJWFrugl5z2Ej_52d&ab_channel=CursoemV%C3%ADdeo', tags: ['HTML', 'CSS', 'Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 1000, nome: '🍪AJUDA AÍ!!⭐', tipo: 'ad', categoria: 'Biscoitagem', descricao: '🍪 Se você gosta de explorar esta selva de vasto conhecimento do JAMANJO e quer mandar aquele carinho, entra ali no repositório e deixa uma estrelinha! É fácil, rápido, de graça e a gente adora! ⭐', link: 'https://github.com/rafaellindemann/rafaellindemann.github.io', tags: ['⭐', '🍪', 'ads', 'Biscoitagem', 'JAMANJO', '💪','🙏','🙌','🤜🤛'] },
      { id: 6, nome: '🌳 Curso em Vídeo, JavaCript para Iniciantes', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O basicão de JavaScript muito bem visto com o padrão Guanabara de qualidade', link: 'https://www.youtube.com/watch?v=1-w1RfGIov4&list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1&ab_channel=CursoemV%C3%ADdeo', tags: ['JS','Curso', 'Youtube', 'Guanabara', 'CursoEmVídeo', 'SentaEAssiste'] },
      { id: 7, nome: 'Curso em Vídeo, Git e GitHub', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O Curso de Git e Github do Guanabara, usando o GitHub Desktop (sem linha de comando)', link: 'https://www.youtube.com/watch?v=xEKo29OWILE&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&ab_channel=CursoemV%C3%ADdeo', tags: ['CursoEmVídeo', 'Guanabara', 'Git', 'GitHub', 'GitHubDesktop'] },
      { id: 8, nome: 'Curso em Vídeo - Lógica de Programação', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'O famoso curso de lógica de programação do Guanabara. Infelizmente ele usa o VisualG na maior parte, mas se abstrair isso super vale a pena! De bônus, o curso inicia com o maravitop Scratch!', link: 'https://www.youtube.com/watch?v=8mei6uVttho&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV&ab_channel=CursoemV%C3%ADdeo', tags: ['Lógica', 'Scratch', 'Guanabara', 'VisualG'] },
      { id: 10, nome: '⚠ devSamurai', tipo: 'destaque', categoria: 'Curso', descricao: 'Só até DEZEMBRO DE 2025: o devSamurai resolveu fechar a devSamurai e deixou disponível para download todos os cursos da plataforma, mas é só até o final do ano. Corre lá pra conferir porque tem muita coisa!', link: 'https://class.devsamurai.com.br/', tags: ['Muitos cursos', 'tempoLimitado', 'NãoPerde'] },
      { id: 9, nome: 'freeCodeCamp', tipo: 'normal', categoria: 'Curso', descricao: 'Muito curso da gringa, super completos e com uma galera muito forte. Os cursos são muito completos, grandes, gratuitos, com certificados gratuitos e em inglês. O site conta com tradução para o português. Chegou a hora de pedir desculpas ao Guanabara por dizer que ele “enrola demais” nas explicações e mostrar que tu tem o que precisa pra dominar a arte da programação. Não deixa de ver o canal do freeCodeCamp aqui no outro quadradinho.', link: 'https://www.freecodecamp.org/', tags: ['Muitos cursos', 'Certificados', 'Tutoriais', 'freeCodeCamp'] },
      { id: 11, nome: 'Canal do freeCodeCamp', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Muito curso da gringa, super completos e com uma galera muito forte. Os cursos são muito completos, grandes, gratuitos, com certificados gratuitos e em inglês. O próprio youtube gera legendas automáticas em português então o inglês não vai ser problema. Chegou a hora de pedir desculpas ao Guanabara por dizer que ele “enrola demais” nas explicações e mostrar que tu tem o que precisa pra dominar a arte da programação. Não deixa de ver o site do freeCodeCamp aqui no outro quadradinho.', link: 'https://www.youtube.com/@freecodecamp', tags: ["freeCodeCamp", 'Cursos', 'Tutoriais'] },
      { id: 12, nome: 'Futuro Dev - Jhon', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Em vez de um canal ensinando a programar, o que tu acha de um mostrando a história de alguém que tá na mesma que tu: aprendendo a programar!', link: 'https://www.youtube.com/@futuroDevJohn', tags: ['Iniciante', 'Carreira', 'Frontend', 'Backend', 'Choradeira'] },
      { id: 13, nome: 'dpw', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Ótimo canal com curso, dicas e tutoriais sobre Frontend (HTML+CSS+JS)', link: 'https://www.youtube.com/channel/UCdHcHgSrWidiOg-mNFNB1Nw', tags: ['Frontend', 'Tutoriais', 'HTML', 'CSS', 'JS'] },
      { id: 14, nome: '🌳 Dicionário do programador, do CódigoFonteTV', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Melhor oportunidade para ouvir falar das principais tecnologias do momento.', link: 'https://www.youtube.com/watch?v=hlgm_1Bzt-4&list=PLVc5bWuiFQ8GgKm5m0cZE6E02amJho94o&ab_channel=C%C3%B3digoFonteTV', tags: ['CulturaDev'] },
      { id: 15, nome: 'Curso de lógica em JavaScript do CFBCursos', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Curso gigaaaaaante de lógica com JavaScript do Tio CFB.', link: 'https://www.youtube.com/watch?v=lcKo-ycLDNw&list=PLx4x_zx8csUj3IbPQ4_X5jis_SkCol3eC', tags: ['Curso', 'Lógica', 'JS'] },
      { id: 16, nome: 'Javascript Essencial - Conceitos iniciais, RBtech', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Curso rapidão de JavaScript', link: 'https://www.youtube.com/watch?v=ipHuSfOYhwA&list=PLInBAd9OZCzxl38aAYdyoMHVg0xCgxrRx&ab_channel=RBtech', tags: ['Curso', 'JS'] },
      { id: 17, nome: 'Cursinho de HTML e CSS, RBtech', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Cursinho antigo de HTML, mas ainda tem seu valor.', link: 'https://www.youtube.com/watch?v=iZ1ucWosOww', tags: ['HTML', 'Curso'] },
      { id: 18, nome: 'Curso Lógica de programação em VisualG, RBtech', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Curso de lógica em VisualG do RBtech', link: 'https://www.youtube.com/watch?v=Ds1n6aHchRU', tags: ['Curso', 'Lógica', 'VisualG'] },
      { id: 19, nome: 'Lucas Montano, do canal Lucas Montano ', tipo: 'normal', categoria: '', descricao: 'Baita canal do Lucas Montano, do canal Lucas Montano. Fala principalmente de carreira e desenvolvimento para dispositivos móveis, mas muito mais também', link: 'https://www.youtube.com/@LucasMontano', tags: ['Variedades', 'CulturaDev', 'Mobile', 'Android', 'MuitaCoisa'] },
      { id: 20, nome: 'Fabio Akita', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Ciência da computação, tecnologia e puxões de orelha. Canal obrigatório, mesmo que não goste:', link: 'https://www.youtube.com/@Akitando', tags: ['Ciência da Computação', 'Tecnologia', 'Tudo'] },
      { id: 21, nome: 'Filipe Deschamps', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Talvez o canal dev mais influente do Brasil. Mesmo que esteja em uma fase mais coach quântico, ainda tem seu valor.', link: 'https://www.youtube.com/@FilipeDeschamps', tags: ['Variedades', 'JS', 'Coach'] },
      { id: 22, nome: 'Gabriel Pato', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Ótimo canal sobre Segurança e Hacking', link: 'https://www.youtube.com/@GabrielPato', tags: ['Hacking', 'Segurança'] },
      { id: 23, nome: 'TecMundo', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Notícias do mundo da tecnologia', link: 'https://www.youtube.com/@tecmundo/featured', tags: ['Notícias', 'Tecnologia'] },
      { id: 24, nome: 'TecMundo - Playlist A história da Tecnologia', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Loucamente interessante saber de onde veio isso tudo aí que a gente brinca hoje.', link: 'https://www.youtube.com/playlist?list=PL7cCKVGMzqmbyaouQulXxUJLdwW4qBMpp', tags: ['História', 'Empresas', 'Tecnologias'] },
      { id: 25, nome: '8 jogos de CSS', tipo: 'normal', categoria: 'Jogos', descricao: 'Artigo no dev.to apresentando 8 games pra aprender CSS brincandinho.', link: 'https://dev.to/devmount/8-games-to-learn-css-the-fun-way-4e0f', tags: ['Jogos', 'CSS'] },
      { id: 26, nome: 'Code Combat', tipo: 'normal', categoria: 'Jogos', descricao: 'Baita plataforma para jogar aprendendo lógica, JavaScript, Python e muito mais...', link: 'https://codecombat.com/', tags: ['Curso', 'Game', 'AprenderJogando', 'JS', 'Python', 'Lógica'] },
      { id: 27, nome: 'spacecoding apresenta: 5 jogos para aprender programação', tipo: 'normal', categoria: 'Jogos', descricao: 'Vídeo da Gi do spacecoding apresentando 5 jogos para aprender programação e afins.', link: 'https://www.instagram.com/p/CjbJmfSgG6X/', tags: ['Instagram', 'AprenderJogando'] },
      { id: 28, nome: 'code.clash: 3 free games to learn programming', tipo: 'normal', categoria: 'Jogos', descricao: 'Vídeo no insta trazendo 3 games pra aprender programação.', link: 'https://www.instagram.com/p/Cg_0GgQjAna/', tags: ['Instagram', 'AprenderJogando'] },
      { id: 29, nome: 'Fundação Bradesco', tipo: 'normal', categoria: 'Curso', descricao: 'Uma infinidade de cursos gratuitos sobre desenvolvimento', link: 'https://www.ev.org.br/areas-de-interesse/programacao', tags: ['Curso', 'Bradesco'] },
      { id: 30, nome: 'Rocketseat Discover', tipo: 'normal', categoria: 'Curso', descricao: 'A amostra grátis da Rocketseat', link: 'https://www.rocketseat.com.br/discover?gclid=Cj0KCQjw2_OWBhDqARIsAAUNTTF4QGXDJwj_KJE-HxhSp_WKdUlF58ZFQ98TW8abc6vAOBvimKggUv4aAsgnEALw_wcB', tags: ['Curso', 'Rocketseat', 'Frontend', 'HTML', 'CSS', 'JS', 'Git', 'GitHub'] },
      { id: 31, nome: 'Dio', tipo: 'normal', categoria: 'Curso', descricao: 'Tem alguns cursos legais no plano gratuito. Te inscreve lá pra ver.', link: 'https://www.dio.me/', tags: ['Dio', 'CursosGratis', 'AmostraGratis'] },
      { id: 32, nome: 'W3Schools', tipo: 'normal', categoria: 'Sites', descricao: 'Dá pra encarar como documentação (e curso) de várias linguagens de programação.', link: 'https://www.w3schools.com/', tags: ['HTML', 'JS', 'CSS', 'Documentação', 'Curso', 'Tutorial', 'Exercícios'] },
      { id: 33, nome: 'MDN', tipo: 'normal', categoria: 'Sites', descricao: 'O velho testamento da programação. Pode assumir como a documentação nua e crua.', link: 'https://developer.mozilla.org/pt-BR/', tags: ['HTML', 'JS', 'CSS', 'Documentação', 'Curso', 'Tutorial', 'Exercícios'] },
      { id: 34, nome: 'MDN: Guia JavaScript', tipo: 'normal', categoria: 'Curso', descricao: 'O Guia de JavaScript preparado pela galera da Mozilla. Aprendizado garantido.', link: 'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide', tags: ['MDN', 'Mozilla', 'JS'] },
      { id: 35, nome: 'MDN: Aprendendo desenvolvimento web', tipo: 'normal', categoria: 'Curso', descricao: 'O cursão de frontend da Mozilla.', link: 'https://developer.mozilla.org/pt-BR/docs/Learn', tags: ['MDN', 'Mozilla', 'JS', 'HTML', 'CSS'] },
      { id: 36, nome: 'CSS Reference: A free visual guide to CSS', tipo: 'normal', categoria: 'Site', descricao: 'Baita referência para CSS. Simples, bonita, visual...', link: 'https://cssreference.io/', tags: ['CSS'] },
      { id: 37, nome: 'Minicurso grátis do Sujeito Programador', tipo: 'normal', categoria: 'Curso', descricao: 'Um minicurso oferecido pelo SujeitoProgramador com uma aula HTML, uma de CSS e uma de JS.', link: 'https://sujeitoprogramador.com/minicurso/?ref=D72629827B&hsrc=bWluaWN1cnNvcHJv', tags: ['Curso', 'HTML', 'CSS', 'JS', 'SujeitoProgramador'] },
      { id: 38, nome: 'Curso Git e GitHub - Curso 100% Gratuito - Sujeito Programador', tipo: 'normal', categoria: 'Curso', descricao: 'Curso gratuito sobre Git e GitHub do Sujeito Programador.', link: 'https://sujeitoprogramador.com/curso-git/?ref=B12785145N', tags: ['Git', 'GitHub', 'SujeitoProgramador'] },
      { id: 39, nome: 'Introdução a HTML/CSS na Khan Academy', tipo: 'normal', categoria: 'Curso', descricao: 'Ótimo curso de HTML e CSS', link: 'https://pt.khanacademy.org/computing/computer-programming/html-css#intro-to-html', tags: ['Frontend', 'HTML', 'CSS'] },
      { id: 40, nome: 'Um guia para iniciantes na área de web - Tableless', tipo: 'normal', categoria: 'Curso', descricao: 'Curso massa e muito completo contemplando o básico de wec, HTML, CSS e JS. Tudo feito com carinho pela comunidade brasileira.', link: 'http://tableless.github.io/iniciantes/', tags: ['Web', 'HTML', 'CSS', 'JS', 'Frontend'] },
      { id: 41, nome: 'Cod3r', tipo: 'normal', categoria: 'Curso', descricao: 'Um monte de cursos massa, com vários importantes gratuitos pra gente aproveitar sem moderação.', link: 'https://www.cod3r.com.br/collections?category=cursos-gratuitos', tags: ['Curso', 'Gratis'] },
      { id: 42, nome: 'Blog UX/UI', tipo: 'normal', categoria: 'Site', descricao: 'Blog criado pra caçar matrículas para um curso caro e com cara de golpinho, mas tem muito material pra aprender sobre Interface de Usuário e Experiência de Usuário no blog.', link: 'https://gabrielsilvestri.com.br/blog/', tags: ['UX/UI'] },
      { id: 43, nome: 'spacecoding: 1001 cursos online gratuitos de tecnologia no exterior', tipo: 'normal', categoria: 'Curso', descricao: 'Videozinho da Gi trazendo algumas possibilidades de estudar na gringa virtualmente', link: 'https://www.instagram.com/p/CjVR1RjAMx9/', tags: ['Curso', 'Instagram'] },
      { id: 44, nome: 'gui_dev_: 4 sites para aprender programação GRÁTIS', tipo: 'normal', categoria: 'Curso', descricao: 'O cara mandou 4 sites pra aprender a zero real.', link: 'https://www.instagram.com/p/ChYAEbhPO_i/', tags: ['Curso', 'Instagram'] },
      { id: 45, nome: 'Tech Guide', tipo: 'normal', categoria: 'Carreira', descricao: 'Um guia da Alura que pretende mostrar o que você precisa aprender para ser um profissional "em T" nas mais diversas área da tecnologia.', link: 'https://techguide.sh/', tags: ['ProfissionalEmT', 'Alura', 'GuiaDeCarreira'] },
      { id: 46, nome: 'Roadmap.sh', tipo: 'normal', categoria: 'Carreira', descricao: 'O Roadmap original. A ideia é apresentar um mapa da sua jornada de aprendizado de uma carreira ou tecnologia. O mapa mostra onde tu vai chegar, o que tu precisa aprender e vai indicando diversos recursos pra te ensinar a cada etapa do teu desenvolvimento.', link: 'https://roadmap.sh/', tags: ['RoadMap', 'OQueAprender', 'OndeAprender'] },
      { id: 47, nome: 'FreeFrontend', tipo: 'normal', categoria: 'Repositórios', descricao: 'Infinitos repositórios de lindos componentes (principalmente) CSS para usar nas suas criações.', link: 'https://freefrontend.com/', tags: ['CSS', 'HTML', 'Frontend', 'Componentes'] },
      { id: 48, nome: 'Pexels', tipo: 'normal', categoria: 'Imagens', descricao: 'Fotos profissionais gratuitas', link: 'https://www.pexels.com/pt-br/', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 49, nome: 'Unsplash', tipo: 'normal', categoria: 'Imagens', descricao: 'Fonte de recursos visuais da internet. Fornecidos por criadores de todo o mundo.', link: 'https://unsplash.com/pt-br', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 50, nome: 'Freepik', tipo: 'normal', categoria: 'Imagens', descricao: 'Imagens grátis', link: 'https://br.freepik.com/', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 51, nome: 'Rawpixel', tipo: 'normal', categoria: 'Imagens', descricao: 'Mais imagens grátis', link: 'https://www.rawpixel.com/?feed=creative-feed&page=1&sort=shuffle', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 52, nome: 'Pixabay', tipo: 'normal', categoria: 'Imagens', descricao: 'Mais de 1 milhão de imagens, fotos e vídeos em alta qualidade para seus projetos.', link: 'https://pixabay.com/pt/', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 53, nome: 'Libreshot', tipo: 'normal', categoria: 'Imagens', descricao: 'I am Martin and you can download my photos for free.', link: 'https://libreshot.com/', tags: ['Imagens', 'Galeria', 'Fotos'] },
      { id: 54, nome: 'Icon Archive', tipo: 'normal', categoria: 'Imagens', descricao: 'Over 800,000 free icons / 2,517 iconpacks. Without login, without subscription', link: 'https://iconarchive.com/', tags: ['Icons'] },
      { id: 55, nome: 'Favicon.cc', tipo: 'normal', categoria: 'Imagens', descricao: 'Ferramenta para criar favicon', link: 'https://www.favicon.cc/', tags: ['Favicon', 'Gerador', 'Ferramenta'] },
      { id: 56, nome: 'Favicon.io', tipo: 'normal', categoria: 'Imagens', descricao: 'Melhor ferramenta para criar favicon', link: 'https://favicon.io/', tags: ['Favicon', 'Gerador', 'Ferramenta'] },
      { id: 57, nome: 'lordicon', tipo: 'normal', categoria: 'Imagens', descricao: 'Galeria de Ícones para usar em seus sites ou apps', link: 'https://lordicon.com/', tags: ['Icons'] },
      { id: 58, nome: 'florinpop17: App ideas collection', tipo: 'normal', categoria: 'Repositórios', descricao: 'Quer praticar em algo real mas não sabe o que fazer? O florinpop17 resolve! Nesse repositório tu vai encontrar um monte de ideias para projetos reais. Tudo super completo, com requisitos, user histories e muito mais!', link: 'https://github.com/florinpop17/app-ideas', tags: ['Ideias', 'Projetos', 'Metodologia'] },
      { id: 59, nome: 'florinpop17: mais ideias curtas', tipo: 'normal', categoria: 'Repositórios', descricao: 'Ele foi desafiado a completar 10 projetos em uma hora :D', link: 'https://github.com/florinpop17/10-projects-1-hour', tags: ['Ideias', 'Projetos'] },
      { id: 60, nome: '3 projetos de nível iniciante que geram até $3000 por Mês', tipo: 'normal', categoria: 'Repositórios', descricao: 'Mais ideias pra projetos, desta vez com promessas de $$', link: 'https://www.youtube.com/watch?v=n3tMEOw9KGY', tags: ['Ideias'] },
      { id: 61, nome: 'HTMLrev', tipo: 'normal', categoria: 'Repositórios', descricao: 'Galeria de templates de sites.', link: 'https://htmlrev.com/', tags: ['Templates', 'HTML', 'CSS', 'Bootstrap'] },
      { id: 62, nome: 'Flexplorer', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Um simulador de flexbox muito louco! (Na home tem mais coisa legal: https://bennettfeely.com/)', link: 'https://bennettfeely.com/flexplorer/', tags: ['Simulador', 'Flexbox', 'css'] },
      { id: 63, nome: 'Links sobre CSS', tipo: 'normal', categoria: 'Site', descricao: 'Um repositório (velho) cheio de links para recursos úteis relacionados ao CSS.', link: 'https://github.com/marcelabomfim/CSSEHFODA', tags: ['CSS'] },
      { id: 64, nome: '🌳🌳 FLEXBOX FROGGY', tipo: 'normal', categoria: 'Jogos', descricao: 'Melhor maneira pra entender flexbox', link: 'https://flexboxfroggy.com/', tags: ['Jogos', 'CSS', 'flexbox'] },
      { id: 65, nome: 'Flexbox Defense', tipo: 'normal', categoria: 'Jogos', descricao: 'Jogo estilo tower defense pra treinar flexbox. Muito bom!', link: 'http://www.flexboxdefense.com/', tags: ['Jogos', 'CSS', 'flexbox'] },
      { id: 66, nome: 'CSS Diner', tipo: 'normal', categoria: 'Jogos', descricao: 'Game pra treinar CSS e seletores.', link: 'https://flukeout.github.io/', tags: ['Jogos', 'CSS'] },
      { id: 67, nome: 'Grid Garden', tipo: 'normal', categoria: 'Jogos', descricao: 'O irmão grid do Flexbox Frog ', link: 'https://cssgridgarden.com/', tags: ['Jogos', 'CSS', 'Grid'] },
      { id: 68, nome: 'eBook Eloquent JavaScript', tipo: 'normal', categoria: 'Livros', descricao: 'Eloquent JavaScript (on line)', link: 'https://eloquentjavascript.net/', tags: ['Livro', 'eBook', 'JS'] },
      { id: 69, nome: 'eBook Eloquent JavaScript - Versão traduzida pt-br', tipo: 'normal', categoria: 'Livros', descricao: 'Eloquent JavaScript (on line)', link: 'https://github.com/braziljs/eloquente-javascript', tags: ['Livro', 'eBook', 'JS', 'BrazilJS'] },
      { id: 70, nome: 'Piskel', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Editor online de sprites animados e pixel art.', link: 'https://www.piskelapp.com/', tags: ['PixelArt', 'Imagens', 'Sprites'] },
      { id: 71, nome: 'Mixamo', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Criador de personagens 3d animados, para games, filmes ou seja lá o que tu imaginar...', link: 'https://www.mixamo.com/#/', tags: ['Sprites', 'Sprites3D'] },
      { id: 72, nome: 'VSCode online', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Um VSCode totalmente online pra usar quando for visitar a vó.', link: 'https://vscode.dev/', tags: ['IDE', 'VSCode'] },
      { id: 73, nome: 'GDB Online', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Editor e debugger online para um monte de linguagens novas e velhas.', link: 'https://www.onlinegdb.com/', tags: ['IDE'] },
      { id: 74, nome: 'replit', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Mistura marota de editor de códigos, IA e rede social.', link: 'https://replit.com/', tags: ['IDE'] },
      { id: 75, nome: 'Dcoder', tipo: 'normal', categoria: 'Ferramentas', descricao: 'IDE online muito legalzinha. Tem até desafios e exercícios. Tem app pra programar no celular, sincronizado com a conta da web.', link: 'https://code.dcoder.tech/', tags: ['IDE'] },
      { id: 76, nome: 'CODEPEN', tipo: 'normal', categoria: 'Ferramentas', descricao: 'The best place to build, test, and discover front-end code. CodePen is a social development environment for front-end designers and developers. Build and deploy a website, show off your work, build test cases to learn and debug, and find inspiration.', link: 'https://codepen.io/', tags: ['IDE'] },
      { id: 77, nome: 'beecrowd', tipo: 'normal', categoria: 'Exercícios', descricao: 'Milhares de exercícios para praticar programação', link: 'https://www.beecrowd.com.br/', tags: ['Exercícios'] },
      { id: 78, nome: 'DevChallenge', tipo: 'normal', categoria: 'Exercícios', descricao: 'Mais um site de desafios para praticar.', link: 'https://www.devchallenge.com.br/', tags: ['Exercícios'] },
      { id: 79, nome: 'Dcoder Challenges', tipo: 'normal', categoria: 'Exercícios', descricao: 'Uma lista imensa de exercícios para praticar algoritmos clássicos. Estão divididos entre Fácil, Médio e Difícil.', link: 'https://code.dcoder.tech/challenges', tags: ['Exercícios', 'Dcoder', 'IDE'] },
      { id: 80, nome: 'HackerRank', tipo: 'normal', categoria: 'Exercícios', descricao: 'O mais conhecido dos sites de desafios de programação. Muito utilizado em entrevistas e, consequentemente, para praticar para elas também.', link: 'https://www.hackerrank.com/', tags: ['Exercícios'] },
      { id: 81, nome: 'OsProgramadores/desafios', tipo: 'normal', categoria: 'Exercícios', descricao: 'Uma ótima lista de edsafios bem complicadinhos...', link: 'https://osprogramadores.com/desafios/', tags: ['Exercícios'] },
      { id: 82, nome: 'Lista de exercícios sobre vetores do Prof. Eduardo Silvestri', tipo: 'normal', categoria: 'Exercícios', descricao: 'Uma bela lista com 31 exercícios para praticar o uso de vetorers. Sugiro tentar resolver com manipulação dos vetores primeiro (lógica), depois usando os métodos de array da linguagem (programação) ', link: 'https://docplayer.com.br/8274125-Lista-de-exercicios-vetores.html', tags: ['Exercícios'] },
      { id: 83, nome: 'StackOverflow', tipo: 'normal', categoria: 'Fóruns', descricao: 'A mãe dos programadores. Perdeu um pouco de relevância com o nascimento do chatGPT mas ainda é muito importante pra nós, principalmente nos problemas mais complexos.', link: 'https://stackoverflow.com/questions', tags: ['FullStackOverflow'] },
      { id: 84, nome: 'StackOverflow-pt', tipo: 'normal', categoria: 'Fóruns', descricao: 'O feudo em português da StackOverflow', link: 'https://pt.stackoverflow.com/', tags: ['FullStackOverflow'] },
      { id: 85, nome: 'GUJ', tipo: 'normal', categoria: 'Fóruns', descricao: 'Versão organizada e bonitinha da StackOverflow. Quase ninguém usa mais, mas todo o conhecimento que já foi compartilhado continua lá.', link: 'https://www.guj.com.br/', tags: ['Alura'] },
      { id: 86, nome: 'HipstersPontoTech', tipo: 'normal', categoria: 'Podcasts', descricao: 'O  maior e mais badalado podcast de tecnologia do Brasil', link: 'https://hipsters.tech/', tags: ['Alura'] },
      { id: 87, nome: 'PodProgramar', tipo: 'normal', categoria: 'Podcasts', descricao: 'Um dos melhores e feito somente por elas!', link: 'https://podprogramar.com.br/', tags: ['MulheresNaTecnologia'] },
      { id: 88, nome: 'devnaestrada', tipo: 'normal', categoria: 'Podcasts', descricao: 'Galera gente boa e manja do que tá falando.', link: 'https://devnaestrada.com.br/', tags: ['PodcastDeGalera'] },
      { id: 89, nome: '<podTag/>', tipo: 'normal', categoria: 'Podcasts', descricao: 'Muita coisa de carreira tech, principalmente no exterior. Mas muito mais que isso também. Depois do falecimento do plano free do heroku, o site saiu do ar. Vou deixar aqui o link do canal do Youtube, mas uma busca por podtag no google rapidamente leva a mais um monte de mídias.', link: 'https://www.youtube.com/@podtagpodcast5387/featured', tags: ['Carreira', 'DevNoExterior'] },
      { id: 90, nome: 'FalaDev da Rocketseat', tipo: 'normal', categoria: 'Podcasts', descricao: 'A Rocketseat sempre traz conteúdo aprofundado e de qualidade.', link: 'https://open.spotify.com/show/3TNsKUGlP9YbV1pgy3ACrW', tags: ['Rocketseat'] },
      { id: 91, nome: 'QuebraDev', tipo: 'normal', categoria: 'Podcasts', descricao: 'Um coletivo que tem como objetivo democratizar a informação para a periferia.', link: 'https://quebra.dev/', tags: ['DevDaQuebrada'] },
      { id: 92, nome: 'PodQuest', tipo: 'normal', categoria: 'Podcasts', descricao: 'Um baita Podcast com uma galera muito forte da indústria mundial dos games. Falava de mercado, desenvolvimento, games... Acabou, mas seu legado continua lá e o servidor do discord continua ativo.', link: 'http://www.podquest.com.br/', tags: ['Games', 'GameDev', 'Discord'] },
      { id: 93, nome: 'Lambda-3 podcast', tipo: 'normal', categoria: 'Podcasts', descricao: 'Podcast brabo!', link: 'https://www.lambda3.com.br/lambda3-podcast/', tags: ['TIVIT'] },
      { id: 94, nome: 'cabeça de lab', tipo: 'normal', categoria: 'Podcasts', descricao: 'O podcast do luizalabs. Super vale a pena conferir', link: 'https://www.cabecadelab.com.br/', tags: ['luizalabs', 'magalu'] },
      { id: 95, nome: 'Newsletter do Deschamps', tipo: 'normal', categoria: 'Balaio', descricao: 'Um belo compilado sobre tecnologia pra quem não tem tempo e/ou é preguiçoso mas tem consciência de que precisa se manter atualizado', link: 'https://filipedeschamps.com.br/newsletter', tags: ['Newsletter', 'Deschamps'] },
      { id: 96, nome: 'LIVE: Quando me tornei um Programador Profissional (A História de 16 Programadores)', tipo: 'normal', categoria: 'Balaio', descricao: 'Foi legal conhecer a história de vários dos programadores mais famosinhos da atualidade.', link: 'https://www.youtube.com/watch?v=eUwiTnK0EA0', tags: ['CDFTV', 'Alura', 'Cod3r', 'Akita', 'Loiane', 'LucasMontano', 'Balta', 'Branas', 'Attekita', 'NetoMarin'] },
      { id: 97, nome: 'UmÓtimo-artigo_sobre_AsFormasMais-comuns_para-CombinarPalavrasEm_programacao', tipo: 'normal', categoria: 'Balaio', descricao: 'Artigo apresentando as conveções de nomenclaturas mais comuns e suas principais aplicações.', link: 'https://visualdicas.blogspot.com/2021/05/quais-as-formas-mais-populares-para.html?fbclid=IwAR3A5IxqS3U_wZceDqjOpFVgFGlIAJCDKCNVbtgdpfXccZZl7U0LffOt8Js', tags: ['camelCase', 'PascalCase', 'snake_case', 'kebab-case'] },
      { id: 98, nome: 'perifacode/conteudo-gratuito', tipo: 'normal', categoria: 'Balaio', descricao: 'Um repositório no GitHub com o mesmo intuito desta página.', link: 'https://github.com/perifacode/conteudo-gratuito', tags: ['Cursos', 'Desafios', 'Dicas'] },
      { id: 99, nome: 'Páginas/perfis/hashtags e afins interessantes aí pelas redes', tipo: 'normal', categoria: 'Redes', descricao: 'São vários então juntei estes links em uma página só. Vale a pena transformar suas redes em algo um pouco mais interessante do que fotos de pratos e pessoas com pouca roupa...', link: 'https://rafaellindemann.notion.site/P-ginas-perfis-hashtags-e-afins-interessantes-a-pelas-redes-2c2324b387cf40ddafc437fe331ad6cd?pvs=4', tags: ['Instagram'] },
      { id: 100, nome: 'tabnews', tipo: 'normal', categoria: 'Fóruns', descricao: 'Meio fórum de discussão, meio plataforma de artigos... ', link: 'https://www.tabnews.com.br/', tags: ['Fórum','Mídias', 'Deschamps'] },
      { id: 101, nome: 'dev.to', tipo: 'normal', categoria: 'Fóruns', descricao: 'Muito mais uma plataforma de divulgação de artigos na área de desenvolvimento do que um fórum, mas também dá pra enxergar o dev.to como um fórum :D', link: 'https://dev.to/', tags: ['Fórum', 'Mídias', 'Artigos', 'Discussão', 'Inglês', 'Português'] },
      { id: 102, nome: '🌳🌳 Fernanda Kipper | Dev', tipo: 'normal', categoria: 'Canal Youtube', descricao: 'Ativa o sininho que ela é demais! Um dos pontos fortes é ela resolvendo desafios de entrevistas técnicas, mas tá longe de ser só isso. Aproveita e espia os vídeos que ela faz para os membros que pagam 5 pila por mês...', link: 'https://www.youtube.com/@kipperdev', tags: ['Canal', 'Kipper', 'React', 'Angular', 'Java', 'Projetos', 'ManjaMuito', 'Carreira'] },
      { id: 103, nome: 'Repositório free-for-dev', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Mais ou menos 18 vidas são necessárias para só testar tudo que está listado lá: de hospedagem, ferramentas, softwares, plataformas, APIs, armazenamento... Tudo de GRÁTIS! ', link: 'https://github.com/ripienaar/free-for-dev', tags: ['Repositório', 'Ferramentas', 'Grátis', 'Free', 'MuitaCoisa'] },
      { id: 104, nome: 'Smart UI Studio', tipo: 'normal', categoria: 'Repositórios', descricao: 'Um site daqueles de influencers mostrando pequenas coisas de frontend pra te inspirar e abrilhantar teu projeto.', link: 'https://www.smartinfogl.com/', tags: ['Frontend', 'Tips', 'HTML', 'CSS', 'Dicas', 'Repositório', 'Animações'] },
      { id: 105, nome: 'shields.io', tipo: 'normal', categoria: 'Imagens', descricao: 'Aqueles badgezinhos bunitinhos que a galera gosta de colocar no perfil do GitHub.', link: 'https://shields.io/', tags: ['Badges', 'GitHub', 'Repositório'] },
      { id: 106, nome: 'Repositório: Badges4-README.md-Profile', tipo: 'normal', categoria: 'Imagens', descricao: 'Uma seleção daqueles badgezinhos bunitinhos que a galera gosta de colocar no perfil do GitHub.', link: 'https://github.com/alexandresanlim/Badges4-README.md-Profile', tags: ['Badges', 'GitHub', 'Repositório'] },
      { id: 107, nome: 'Wave - teste de acessibilidade', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Ajuda a encontrar problemas de acessibilidade em seu site.', link: 'https://wave.webaim.org/', tags: ['Acessibilidade', 'Teste'] },
      { id: 108, nome: 'Conversor de cores - HEX <-> RGB', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Converta as suas cores de rgb(223, 78, 57) para #DF4E39 rapidinho e sem tretas', link: 'https://www.rapidtables.com/convert/color/hex-to-rgb.html', tags: ['Cores', 'Design', 'Conversor', 'RGB', 'Hex'] },
      { id: 109, nome: 'Guia Extenso de Programação', tipo: 'normal', categoria: 'Repositórios', descricao: 'Quer aprender alguma coisa de tecnologia? Aqui tem praticamente tudo!', link: 'https://github.com/arthurspk/guiadevbrasil', tags: ['Repositório', 'Recursos', 'Aprender'] },
      { id: 110, nome: 'Brasil Code: Recursos gratuitos para criar sites', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Ótimo artigo em um ótimo blog. Tem muito mais coisa legal lá, vale a pena conferir!', link: 'https://www.brasilcode.com.br/melhores-recursos-gratuitos-para-criar-sites/', tags: ['Ferramentas', 'Recursos', 'Aprender', 'Grátis', 'Frontend'] },
      { id: 111, nome: 'Blog do Sujeito Programador', tipo: 'normal', categoria: 'Sites', descricao: 'Muita coisa boa no blog do Sujeito, principalmente sobre carreira', link: 'https://sujeitoprogramador.com/', tags: ['Blog', 'SujeitoProgramador', 'Carreira'] },
      { id: 112, nome: 'Discord da Comunidade He4rt Developers', tipo: 'normal', categoria: 'Redes', descricao: 'Se tu for obrigado a escolher uma única comunidade pra participar, fecha o olho e vai nessa. Confia...', link: 'https://discord.gg/he4rt', tags: ['RedesSociais', 'Comunidade', 'Discord'] },
      { id: 113, nome: 'javascript.info', tipo: 'normal', categoria: 'Site', descricao: 'Um tutorial/guia bem interessante, completo e dinâmico para o JavaScript', link: 'https://javascript.info/', tags: ['JS', 'Documentação', 'Tutorial'] },
      { id: 114, nome: 'Render: Cloud Application Hosting for Developers', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Host de back end com delicioso free tier', link: 'https://render.com/', tags: ['Host', 'Provedor', 'Backend'] },
      { id: 115, nome: 'Microsoft Learn', tipo: 'normal', categoria: 'Curso', descricao: 'Central de cursos gratuitos da Microsoft. Muita coisa sobre (principalmente, mas não só) C#, Azure, IA, BI, GitHub...', link: 'https://learn.microsoft.com/pt-br/training/?fbclid=IwAR0eu1oD2pFDhq5f0MIZ2MjXFyUdc2W9vMJsQTBogQt3p0bAozoDtJomFLk', tags: ['C#', 'Azure', 'IA', 'BI', 'GitHub', 'Microsoft'] },
      { id: 116, nome: 'eu CAPACITO', tipo: 'normal', categoria: 'Curso', descricao: 'Seleção de cursos gratuitos de tecnologia oferecidos por aí.', link: 'https://www.eucapacito.com.br/pesquisa-cursos', tags: ['euCAPACITO', 'Cursos', 'IBM', 'Google', 'FIAP', 'Microsoft', 'Cisco', 'Oracle'] },
      { id: 117, nome: 'FontAwesome', tipo: 'normal', categoria: 'Imagens', descricao: 'Ícones para usar no front', link: 'https://fontawesome.com/icons', tags: ['Icons', 'Ícones'] },
      { id: 118, nome: '🌳 storyset', tipo: 'normal', categoria: 'Imagens', descricao: 'Um repositório de imagens muito legal. Lá dá pra escolher imagens com um mesmo estilo pra enfeitar teu projeto. Dá pra customizar um monte de coisas nelas também.', link: 'https://storyset.com/', tags: ['Imagens','Repositório', 'SVG', 'PNG',] },
      { id: 119, nome: 'Iconbuddy', tipo: 'normal', categoria: 'Imagens', descricao: 'Meio repositório de Icons, meio ferramenta de busca e edição. Super vale a pena conferir... ', link: 'https://iconbuddy.app/', tags: ['Icons', 'Repositório', 'Icon', 'Imagens'] },
      { id: 120, nome: 'Prompt Engineering Guide', tipo: 'normal', categoria: 'Curso', descricao: 'Ótimo curso de propting de IA para desenvolvedores. Em inglês, mas tu pode traduzir com IA :P.', link: 'https://learnprompting.org/docs/intro', tags: ['IA', 'Prompt', 'InteligenciaArtificial'] },
      { id: 121, nome: 'Neumorphism.io', tipo: 'normal', categoria: 'Repositórios', descricao: 'Gerador de CSSs maneiros e supimpas!', link: 'https://neumorphism.io/#e0e0e0', tags: ['Frontend','CSS', 'Ferramentas','Repositórios', 'Gerador'] },
      { id: 122, nome: '🌳 Iconify', tipo: 'normal', categoria: 'Imagens', descricao: 'Repositório de Ícones, simplão e completão e super organizado.', link: 'https://icon-sets.iconify.design/', tags: ['Icons', 'Repositório', 'Icon', 'Imagens'] },
      { id: 123, nome: 'Flexbox Guia Completo - Origamid', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Tutorial/ferramenta de simulação sobre Flexbox da afamada Origamid', link: 'https://origamid.com/projetos/flexbox-guia-completo/', tags: ['Ferramenta', 'Tutorial', 'Frontend', 'CSS'] },
      { id: 124, nome: 'Grid layout Guia Completo - Origamid', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Tutorial/ferramenta de simulação sobre Grid CSS da afamada Origamid', link: 'https://www.origamid.com/projetos/css-grid-layout-guia-completo/', tags: ['Ferramenta', 'Tutorial', 'Frontend', 'CSS'] },
      { id: 125, nome: 'JS antes do framework - Origamid', tipo: 'normal', categoria: 'Curso Youtube', descricao: 'Excelente playlist com revisão de 10 ítens de JS', link: 'https://www.youtube.com/watch?v=j6iSONAO6sQ&list=PL9rc_FjKlX39T78CUANwmdta_d1CgUtMt&ab_channel=Origamid', tags: ['Curso', 'Origamid', 'Frontend', 'JS', 'Revisão'] },
      { id: 126, nome: ' Cheatsheets da codecademy', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Enorme e organizada coleção das famosas Cheatsheets, mas num nível mais macro, quase um bebê de uma cheatsheet com um roadmap com alguns traços do vizinho tutorial', link: 'https://www.codecademy.com/resources/cheatsheets/all', tags: ['Ferramenta', 'cheatsheet', 'codecademy'] },
      { id: 127, nome: 'Awesome Cheatsheets', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Cheatsheets simples e poderosas, hospedadas no GitHub', link: 'https://lecoupa.github.io/awesome-cheatsheets/', tags: ['Ferramenta', 'cheatsheet'] },
      { id: 128, nome: ' Devhints Cheatsheets', tipo: 'normal', categoria: 'Ferramentas', descricao: 'A mais oldshool das coleções de cheatsheets, super completa e pormenorizada. Acho a ferramenta de pesquisa deles muito confusa, mas um ctrl+f resolve qualquer coisa.', link: 'https://devhints.io/', tags: ['Ferramenta', 'cheatsheet'] },
      { id: 129, nome: '🌳 VS Code Cheatsheets', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Cheatsheet de atalhos de teclado do VS Code', link: 'https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf', tags: ['Ferramenta', 'cheatsheet', 'VSCode'] },
      { id: 130, nome: 'javascriptcheatsheet.org', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Se apresenta como cheatsheet do Javascript, mas eu colocaria tranquilamente como livro ou curso de tão completo e bem feito', link: 'https://www.javascriptcheatsheet.org/', tags: ['Ferramenta', 'cheatsheet', 'curso'] },
      { id: 131, nome: 'project-based-learning', tipo: 'normal', categoria: 'Repositórios', descricao: 'Repositório com uma coleção gigante de projetos guiados em dezenas de linguagens diferentes.', link: 'https://github.com/practical-tutorials/project-based-learning', tags: ['repositório', 'projetos', 'praticar'] },
      { id: 132, nome: 'uiverse.io', tipo: 'normal', categoria: 'Repositórios', descricao: 'Repositório de elementos (botão, input, card...) para abrilhantar qualquer frontend.', link: 'https://uiverse.io/', tags: ['repositório', 'elementos', 'frontend'] },
      { id: 133, nome: 'ui-snippets', tipo: 'normal', categoria: 'Repositórios', descricao: 'Mais um repositório de elementos (botão, input, card...) para abrilhantar qualquer frontend.', link: 'https://app.ui-snippets.com/', tags: ['repositório', 'elementos', 'frontend'] },
      { id: 134, nome: '🌳 Coolors', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Paletas de cores (gerador, seletor, extrator), testador de contraste, gradientes...', link: 'https://coolors.co/', tags: ['Ferramenta', 'cores', 'design', 'paletaDeCores'] },
      { id: 135, nome: 'freesets', tipo: 'normal', categoria: 'Repositórios', descricao: 'Uma versão mais curta, visual e bonita deste progHub. Tem muita ferramenta legal lá, vale a pena a visita!', link: 'https://freesets.dev/', tags: ['repositório', 'elementos', 'frontend', 'links', 'copiaDoProgHub'] },
      { id: 136, nome: '🌳 App Algoritmos', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Incrível simulador de algoritmos para android. Perfeito para entender como os algoritmos mais comuns funcionam!', link: 'https://play.google.com/store/apps/details?id=wiki.algorithm.algorithms', tags: ['Ferramenta', 'algoritmos', 'testeDeMesa', 'simulacao'] },
      { id: 137, nome: '🌳 VisuAlgo.net', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Incrível simulador de algoritmos para android. Perfeito para entender como os algoritmos mais comuns funcionam!', link: 'https://visualgo.net/en', tags: ['Ferramenta', 'algoritmos', 'testeDeMesa', 'simulacao'] },
      { id: 138, nome: 'Raycast Icon Maker', tipo: 'normal', categoria: 'Imagens', descricao: 'Ferramenta muito legal para personalizar ícones.', link: 'https://ray.so/icon', tags: ['Icons', 'Repositório', 'Icon', 'Imagens', 'ferramenta', 'editor'] },
      { id: 139, nome: 'Pattern Monster', tipo: 'normal', categoria: 'Ferramentas', descricao: 'Ótima ferramenta para criar padrões possivelmente bonitos para usar como background. Aprecie muito, mas com cuidado!', link: 'pattern.monster', tags: ['Ferramenta', 'Patterns', 'Background', 'Imagens'] }
    ]
        
        
    const categories = [
        "Curso Youtube", "Canal Youtube", "Curso", "Sites", "Carreira", "Jogos", 
        "Repositórios", "Imagens", "Ferramentas", "Livros", "Exercícios", "Fóruns", 
        "Podcasts", "Redes", "Balaio", "React"
    ];

    const [filteredResources, setFilteredResources] = useState(resources);
    const [filters, setFilters] = useState([]);

    useEffect(() => {
    console.log(filters);
    console.log(filteredResources.length)
    }
,[filters])
  
    const handleFilter = (category) => {
      if (category) {
        const filtered = resources.filter((resource) => resource.categoria === category || resource.tipo ==='ad');
        setFilteredResources(filtered);
        setFilters([category]);
      } else {
        setFilteredResources(resources);
        setFilters([]);
      }
    };

    return (
        <GlobalContext.Provider value={{resources, categories,
            filteredResources, setFilteredResources,
            filters, setFilters,
            handleFilter
        }}>
            {children}
        </GlobalContext.Provider>
    )
}
